"""Hermetic .grammar -> generated parser artifacts (SYSTEMS.md B1/B3)."""

McGrammarInfo = provider(
    fields = {
        "parser_c": "Generated Tree-sitter parser C source.",
        "node_types": "Generated concrete node schema.",
        "semantics": "AgentOS concrete-to-semantic projection.",
        "semantics_c": "Generated runtime semantics data.",
        "manifest": "Version and digest manifest.",
        "language": "Stable runtime language name.",
    },
)

def _mc_grammar_impl(ctx):
    root = ctx.file.root
    module_inputs = []
    module_args = []
    for target, module_id in sorted(ctx.attr.modules.items(), key = lambda item: item[1]):
        files = target.files.to_list()
        if len(files) != 1:
            fail("mc_grammar module %s must provide exactly one file" % target.label)
        module_inputs.append(files[0])
        module_args.extend(["--module", "%s=%s" % (module_id, files[0].path)])

    outs = struct(
        ir = ctx.actions.declare_file(ctx.label.name + "/grammar.ir.json"),
        grammar_json = ctx.actions.declare_file(ctx.label.name + "/grammar.json"),
        parser_c = ctx.actions.declare_file(ctx.label.name + "/parser.c"),
        node_types = ctx.actions.declare_file(ctx.label.name + "/node-types.json"),
        semantics = ctx.actions.declare_file(ctx.label.name + "/semantics.json"),
        semantics_c = ctx.actions.declare_file(ctx.label.name + "/semantics.c"),
        diagnostics = ctx.actions.declare_file(ctx.label.name + "/diagnostics.json"),
        manifest = ctx.actions.declare_file(ctx.label.name + "/manifest.json"),
    )
    args = ctx.actions.args()
    args.add_all(["--root", root.path])
    args.add_all(module_args)
    args.add_all(["--vocabulary", ctx.file.vocabulary.path])
    args.add_all(["--ir", outs.ir.path, "--grammar-json", outs.grammar_json.path])
    args.add_all(["--parser-c", outs.parser_c.path, "--node-types", outs.node_types.path])
    args.add_all(["--semantics", outs.semantics.path, "--diagnostics", outs.diagnostics.path])
    args.add_all(["--semantics-c", outs.semantics_c.path])
    args.add_all(["--manifest", outs.manifest.path])
    all_outputs = [outs.ir, outs.grammar_json, outs.parser_c, outs.node_types, outs.semantics, outs.semantics_c, outs.diagnostics, outs.manifest]
    ctx.actions.run(
        executable = ctx.executable._generator,
        arguments = [args],
        inputs = depset([root, ctx.file.vocabulary] + module_inputs),
        outputs = all_outputs,
        mnemonic = "McGrammarGen",
        progress_message = "Generating parser %{label}",
    )
    return [
        DefaultInfo(files = depset(all_outputs)),
        McGrammarInfo(
            parser_c = outs.parser_c,
            node_types = outs.node_types,
            semantics = outs.semantics,
            semantics_c = outs.semantics_c,
            manifest = outs.manifest,
            language = ctx.attr.language,
        ),
        OutputGroupInfo(
            parser_c = depset([outs.parser_c]),
            node_types = depset([outs.node_types]),
            semantics = depset([outs.semantics]),
            semantics_c = depset([outs.semantics_c]),
            manifest = depset([outs.manifest]),
            inspection = depset([outs.ir, outs.grammar_json, outs.diagnostics]),
        ),
    ]

mc_grammar = rule(
    implementation = _mc_grammar_impl,
    attrs = {
        "root": attr.label(allow_single_file = [".grammar"], mandatory = True),
        "modules": attr.label_keyed_string_dict(allow_files = [".grammar"]),
        "language": attr.string(mandatory = True),
        "vocabulary": attr.label(allow_single_file = [".kdl"], default = "//memcontainers/contracts:syntax.kdl"),
        "_generator": attr.label(default = "//bazel/tools/mc-grammar-gen:mc-grammar-gen", executable = True, cfg = "exec"),
    },
)

def _mc_syntax_registry_impl(ctx):
    header = ctx.actions.declare_file(ctx.label.name + ".h")
    zig = ctx.actions.declare_file(ctx.label.name + ".zig")
    grammars = sorted([target[McGrammarInfo] for target in ctx.attr.grammars], key = lambda info: info.language)
    header_lines = [
        "/* @generated by //bazel:mc_syntax_registry — do not edit. */",
        "#include <tree_sitter/api.h>",
    ]
    zig_lines = [
        "// @generated by //bazel:mc_syntax_registry — do not edit.",
        "const std = @import(\"std\");",
        "pub const Descriptor = struct { name: []const u8, semantics_path: []const u8, manifest_path: []const u8 };",
    ]
    for grammar in grammars:
        header_lines.append("const TSLanguage *tree_sitter_%s(void);" % grammar.language)
        header_lines.append("const uint8_t *mc_syntax_%s_semantics(uint32_t *len);" % grammar.language)
        zig_lines.append("pub extern fn tree_sitter_%s() ?*const anyopaque;" % grammar.language)
        zig_lines.append("pub extern fn mc_syntax_%s_semantics(len: *u32) [*]const u8;" % grammar.language)
    zig_lines.append("pub const descriptors = [_]Descriptor{")
    for grammar in grammars:
        zig_lines.append("    .{ .name = \"%s\", .semantics_path = \"/usr/share/syntax/%s/semantics.json\", .manifest_path = \"/usr/share/syntax/%s/manifest.json\" }," % (grammar.language, grammar.language, grammar.language))
    zig_lines.extend([
        "};",
        "pub fn language(comptime c: type, name: []const u8) ?*const c.TSLanguage {",
    ])
    for grammar in grammars:
        zig_lines.append("    if (std.mem.eql(u8, name, \"%s\")) return @ptrCast(tree_sitter_%s());" % (grammar.language, grammar.language))
    zig_lines.extend(["    return null;", "}"])
    zig_lines.extend(["pub fn semantics(name: []const u8) ?[]const u8 {", "    var len: u32 = 0;"])
    for grammar in grammars:
        zig_lines.append("    if (std.mem.eql(u8, name, \"%s\")) return mc_syntax_%s_semantics(&len)[0..len];" % (grammar.language, grammar.language))
    zig_lines.extend(["    return null;", "}"])
    ctx.actions.write(header, "\n".join(header_lines) + "\n")
    ctx.actions.write(zig, "\n".join(zig_lines) + "\n")
    return [DefaultInfo(files = depset([header, zig])), OutputGroupInfo(header = depset([header]), zig = depset([zig]))]

mc_syntax_registry = rule(
    implementation = _mc_syntax_registry_impl,
    attrs = {"grammars": attr.label_list(providers = [McGrammarInfo], mandatory = True)},
)
