//! Curated integration registry lifted from executor's preset tables.
//!
//! executor is MIT (c) Rhys Sullivan. Per `INVOKE.md`, AgentOS lifts factual metadata and
//! normalization rules, not JavaScript implementation code. These entries are public integration
//! identifiers, names, summaries, icons, and source endpoints/spec URLs used by `/svc/adapters`.
//! Source snapshot: <https://github.com/RhysSullivan/executor> at
//! `44fff2f9db297676b1ec6e6cdabb46a9487a75c5`.
//!
//! executor also publishes an open-ended feed at `https://integrations.sh/api.json`. That is not
//! part of this baked deterministic table; check it later only when the adapter plane has an
//! explicit refresh, cache, and policy contract.

use serde::Serialize;

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub enum RegistryKind {
    #[serde(rename = "openapi")]
    OpenApi,
    #[serde(rename = "microsoft-graph")]
    MicrosoftGraph,
    #[serde(rename = "google-discovery")]
    GoogleDiscovery,
    #[serde(rename = "graphql")]
    GraphQl,
    #[serde(rename = "mcp-remote")]
    McpRemote,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct RegistryEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub summary: &'static str,
    pub kind: RegistryKind,
    pub url: Option<&'static str>,
    pub endpoint: Option<&'static str>,
    pub icon: Option<&'static str>,
    pub featured: bool,
    pub oauth_audience: Option<&'static str>,
    pub scopes: &'static [&'static str],
    pub exact_paths: &'static [&'static str],
    pub path_prefixes: &'static [&'static str],
    pub tag_prefixes: &'static [&'static str],
    /// Curated egress origins (`scheme://host[:port]`) this integration's tools call. The host derives
    /// a connection's credential-egress allowlist from this when the embedder omits `origins`, so the
    /// user only names the capability + key. Curated (our constant), not read from a live spec, so a
    /// tampered upstream spec cannot redirect the credential. Empty ⇒ the embedder must pass `origins`.
    pub servers: &'static [&'static str],
}

/// Set `servers` on an entry built by one of the kind constructors (which default it to `NONE`).
const fn with_servers(mut entry: RegistryEntry, servers: &'static [&'static str]) -> RegistryEntry {
    entry.servers = servers;
    entry
}

pub fn entries() -> &'static [RegistryEntry] {
    REGISTRY
}

pub fn find(id: &str) -> Option<&'static RegistryEntry> {
    REGISTRY.iter().find(|entry| entry.id == id)
}

const NONE: &[&str] = &[];
const MICROSOFT_ICON: &str = "https://www.microsoft.com/favicon.ico";
const GOOGLE_G: &str = "https://fonts.gstatic.com/s/i/productlogos/googleg/v6/192px.svg";
const GOOGLE_PHOTOS_ICON: &str =
    "https://www.gstatic.com/images/branding/product/2x/photos_96dp.png";
const MICROSOFT_GRAPH_OPENAPI_URL: &str =
    "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml";

const fn openapi(
    id: &'static str,
    name: &'static str,
    summary: &'static str,
    url: &'static str,
    icon: &'static str,
    featured: bool,
) -> RegistryEntry {
    RegistryEntry {
        id,
        name,
        summary,
        kind: RegistryKind::OpenApi,
        url: Some(url),
        endpoint: None,
        icon: Some(icon),
        featured,
        oauth_audience: None,
        scopes: NONE,
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    }
}

const fn google(
    id: &'static str,
    name: &'static str,
    summary: &'static str,
    url: &'static str,
    icon: &'static str,
    featured: bool,
    oauth_audience: &'static str,
    scopes: &'static [&'static str],
) -> RegistryEntry {
    RegistryEntry {
        id,
        name,
        summary,
        kind: RegistryKind::GoogleDiscovery,
        url: Some(url),
        endpoint: None,
        icon: Some(icon),
        featured,
        oauth_audience: Some(oauth_audience),
        scopes,
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    }
}

const fn graphql(
    id: &'static str,
    name: &'static str,
    summary: &'static str,
    endpoint: &'static str,
    icon: &'static str,
    featured: bool,
) -> RegistryEntry {
    RegistryEntry {
        id,
        name,
        summary,
        kind: RegistryKind::GraphQl,
        url: Some(endpoint),
        endpoint: Some(endpoint),
        icon: Some(icon),
        featured,
        oauth_audience: None,
        scopes: NONE,
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    }
}

const fn mcp_remote(
    id: &'static str,
    name: &'static str,
    summary: &'static str,
    endpoint: &'static str,
    icon: &'static str,
    featured: bool,
) -> RegistryEntry {
    RegistryEntry {
        id,
        name,
        summary,
        kind: RegistryKind::McpRemote,
        url: Some(endpoint),
        endpoint: Some(endpoint),
        icon: Some(icon),
        featured,
        oauth_audience: None,
        scopes: NONE,
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    }
}

const fn microsoft(
    id: &'static str,
    name: &'static str,
    summary: &'static str,
    icon: &'static str,
    featured: bool,
    audience: &'static str,
    scopes: &'static [&'static str],
    exact_paths: &'static [&'static str],
    path_prefixes: &'static [&'static str],
) -> RegistryEntry {
    RegistryEntry {
        id,
        name,
        summary,
        kind: RegistryKind::MicrosoftGraph,
        url: Some(MICROSOFT_GRAPH_OPENAPI_URL),
        endpoint: Some("https://graph.microsoft.com/v1.0"),
        icon: Some(icon),
        featured,
        oauth_audience: Some(audience),
        scopes,
        exact_paths,
        path_prefixes,
        tag_prefixes: NONE,
        servers: NONE,
    }
}

pub const REGISTRY: &[RegistryEntry] = &[
    with_servers(openapi(
        "stripe",
        "Stripe",
        "Payments, subscriptions, customers, and invoices.",
        "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json",
        "https://stripe.com/favicon.ico",
        true,
    ), &["https://api.stripe.com"]),
    with_servers(
        openapi(
            "github-rest",
            "GitHub REST",
            "Repos, issues, pull requests, actions, and users.",
            "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
            "https://svgl.app/library/github_dark.svg",
            true,
        ),
        &["https://api.github.com"],
    ),
    with_servers(openapi(
        "vercel",
        "Vercel",
        "Deployments, domains, projects, and edge config.",
        "https://openapi.vercel.sh",
        "https://vercel.com/favicon.ico",
        true,
    ), &["https://api.vercel.com"]),
    with_servers(openapi(
        "cloudflare",
        "Cloudflare",
        "DNS, workers, pages, R2, and security rules.",
        "https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json",
        "https://cloudflare.com/favicon.ico",
        true,
    ), &["https://api.cloudflare.com"]),
    with_servers(openapi(
        "neon",
        "Neon",
        "Serverless Postgres: projects, branches, and endpoints.",
        "https://neon.tech/api_spec/release/v2.json",
        "https://neon.tech/favicon/favicon.ico",
        true,
    ), &["https://console.neon.tech"]),
    with_servers(openapi(
        "openai",
        "OpenAI",
        "Models, files, responses, and fine-tuning.",
        "https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml",
        "https://svgl.app/library/openai_dark.svg",
        true,
    ), &["https://api.openai.com"]),
    with_servers(openapi(
        "sentry",
        "Sentry",
        "Error tracking, performance monitoring, and releases.",
        "https://raw.githubusercontent.com/getsentry/sentry-api-schema/main/openapi-derefed.json",
        "https://svgl.app/library/sentry.svg",
        true,
    ), &["https://sentry.io", "https://us.sentry.io", "https://de.sentry.io"]),
    with_servers(openapi(
        "exa",
        "Exa",
        "Web search, similar links, content retrieval, and answers.",
        "https://raw.githubusercontent.com/exa-labs/openapi-spec/refs/heads/master/exa-openapi-spec.yaml",
        "https://exa.ai/images/favicon-32x32.png",
        true,
    ), &["https://api.exa.ai"]),
    with_servers(openapi(
        "exa-websets",
        "Exa Websets",
        "Websets, enrichments, webhooks, and monitors.",
        "https://raw.githubusercontent.com/exa-labs/openapi-spec/refs/heads/master/exa-websets-spec.yaml",
        "https://exa.ai/images/favicon-32x32.png",
        true,
    ), &["https://api.exa.ai"]),
    with_servers(openapi(
        "axiom",
        "Axiom",
        "Log ingestion, querying, datasets, and monitors.",
        "https://axiom.co/docs/restapi/versions/v2.json",
        "https://axiom.co/favicon.ico",
        false,
    ), &["https://api.axiom.co"]),
    with_servers(openapi(
        "asana",
        "Asana",
        "Tasks, projects, teams, and workspace management.",
        "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/asana.com/1.0/openapi.yaml",
        "https://asana.com/favicon.ico",
        false,
    ), &["https://app.asana.com"]),
    with_servers(openapi(
        "twilio",
        "Twilio",
        "SMS, voice, video, and messaging APIs.",
        "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json",
        "https://twilio.com/favicon.ico",
        false,
    ), &["https://api.twilio.com"]),
    with_servers(openapi(
        "digitalocean",
        "DigitalOcean",
        "Droplets, Kubernetes, databases, and networking.",
        "https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml",
        "https://assets.digitalocean.com/favicon.ico",
        false,
    ), &["https://api.digitalocean.com"]),
    with_servers(openapi(
        "petstore",
        "Petstore",
        "Classic OpenAPI demo, no auth required.",
        "https://petstore3.swagger.io/api/v3/openapi.json",
        "https://petstore3.swagger.io/favicon-32x32.png",
        false,
    ), &["https://petstore3.swagger.io"]),
    with_servers(openapi(
        "val-town",
        "Val Town",
        "Vals, runs, blobs, and email/web endpoints.",
        "https://api.val.town/openapi.json",
        "https://www.val.town/favicon.svg",
        false,
    ), &["https://api.val.town"]),
    with_servers(openapi(
        "resend",
        "Resend",
        "Transactional email sending and domain management.",
        "https://raw.githubusercontent.com/resend/resend-openapi/main/resend.yaml",
        "https://resend.com/static/favicons/favicon.ico",
        false,
    ), &["https://api.resend.com"]),
    with_servers(openapi(
        "spotify",
        "Spotify",
        "Tracks, albums, playlists, library, and playback.",
        "https://raw.githubusercontent.com/sonallux/spotify-web-api/refs/heads/main/official-spotify-open-api.yml",
        "https://svgl.app/library/spotify.svg",
        false,
    ), &["https://api.spotify.com"]),
    microsoft(
        "profile",
        "Profile",
        "Signed-in user profile and photo.",
        "https://svgl.app/library/microsoft.svg",
        true,
        "productivity",
        &["User.Read"],
        &["/me", "/me/photo", "/me/photo/$value"],
        NONE,
    ),
    microsoft(
        "me-surface",
        "My Graph Operations",
        "All operation groups rooted under /me.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "productivity",
        &["User.Read"],
        NONE,
        &["/me"],
    ),
    microsoft(
        "mail",
        "Outlook Mail",
        "Messages, folders, attachments, settings, and send mail.",
        "https://svgl.app/library/microsoft-outlook.svg",
        true,
        "productivity",
        &["Mail.ReadWrite", "Mail.Send", "MailboxSettings.ReadWrite"],
        NONE,
        &[
            "/me/messages",
            "/me/mailFolders",
            "/me/sendMail",
            "/me/getMailTips",
            "/me/inferenceClassification",
            "/me/mailboxSettings",
            "/me/outlook",
            "/users/{user-id}/messages",
            "/users/{user-id}/mailFolders",
            "/users/{user-id}/sendMail",
            "/users/{user-id}/outlook",
        ],
    ),
    microsoft(
        "calendar",
        "Outlook Calendar",
        "Calendars, events, and scheduling.",
        "https://svgl.app/library/microsoft-outlook.svg",
        true,
        "productivity",
        &["Calendars.ReadWrite"],
        NONE,
        &[
            "/me/calendar",
            "/me/calendars",
            "/me/calendarGroups",
            "/me/calendarView",
            "/me/events",
            "/me/findMeetingTimes",
            "/me/reminderView",
            "/users/{user-id}/calendar",
            "/users/{user-id}/calendars",
            "/users/{user-id}/calendarGroups",
            "/users/{user-id}/calendarView",
            "/users/{user-id}/events",
            "/users/{user-id}/findMeetingTimes",
            "/users/{user-id}/reminderView",
        ],
    ),
    microsoft(
        "contacts",
        "Outlook Contacts",
        "Contacts, contact folders, and people suggestions.",
        "https://svgl.app/library/microsoft-outlook.svg",
        false,
        "productivity",
        &["Contacts.ReadWrite", "People.Read.All"],
        NONE,
        &[
            "/me/contacts",
            "/me/contactFolders",
            "/me/people",
            "/users/{user-id}/contacts",
            "/users/{user-id}/contactFolders",
            "/users/{user-id}/people",
        ],
    ),
    microsoft(
        "tasks",
        "To Do Tasks",
        "Task lists, task items, and checklist items.",
        "https://svgl.app/library/microsoft-todo.svg",
        false,
        "productivity",
        &["Tasks.ReadWrite"],
        NONE,
        &["/me/todo", "/users/{user-id}/todo"],
    ),
    microsoft(
        "planner",
        "Planner",
        "Plans, buckets, tasks, assignments, and Planner user data.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "productivity",
        &["Tasks.ReadWrite"],
        NONE,
        &["/planner", "/me/planner", "/users/{user-id}/planner", "/groups/{group-id}/planner"],
    ),
    microsoft(
        "files",
        "OneDrive Files",
        "Drives, files, folders, sharing links, and permissions.",
        "https://svgl.app/library/microsoft-onedrive.svg",
        true,
        "files-content",
        &["Files.ReadWrite.All", "Sites.ReadWrite.All"],
        NONE,
        &[
            "/me/drive",
            "/me/drives",
            "/me/followedSites",
            "/users/{user-id}/drive",
            "/users/{user-id}/drives",
            "/groups/{group-id}/drive",
            "/groups/{group-id}/drives",
            "/drives",
            "/shares",
        ],
    ),
    microsoft(
        "excel",
        "Excel Workbooks",
        "Workbook tables, worksheets, ranges, charts, and sessions.",
        "https://svgl.app/library/microsoft-excel.svg",
        false,
        "files-content",
        &["Files.ReadWrite.All"],
        NONE,
        &[
            "/me/drive/items/{driveItem-id}/workbook",
            "/users/{user-id}/drive/items/{driveItem-id}/workbook",
            "/groups/{group-id}/drive/items/{driveItem-id}/workbook",
            "/drives/{drive-id}/items/{driveItem-id}/workbook",
        ],
    ),
    microsoft(
        "sites",
        "SharePoint Sites",
        "Sites, lists, pages, columns, content types, and stores.",
        "https://svgl.app/library/microsoft-sharepoint.svg",
        true,
        "files-content",
        &["Sites.ReadWrite.All"],
        NONE,
        &["/sites"],
    ),
    microsoft(
        "onenote",
        "OneNote",
        "Notebooks, sections, pages, and page content.",
        "https://svgl.app/library/microsoft-onenote.svg",
        false,
        "files-content",
        &["Notes.ReadWrite"],
        NONE,
        &["/me/onenote", "/users/{user-id}/onenote", "/groups/{group-id}/onenote", "/sites/{site-id}/onenote"],
    ),
    microsoft(
        "teams-chat",
        "Teams Chats",
        "Chats, chat messages, installed apps, and members.",
        "https://svgl.app/library/microsoft-teams.svg",
        false,
        "collaboration",
        &["Chat.ReadWrite"],
        NONE,
        &["/me/chats", "/chats"],
    ),
    microsoft(
        "teams-channels",
        "Teams Channels",
        "Teams, channels, channel messages, replies, and joined teams.",
        "https://svgl.app/library/microsoft-teams.svg",
        false,
        "collaboration",
        &["Team.ReadBasic.All", "Channel.ReadBasic.All", "ChannelMessage.Read.All", "ChannelMessage.Send"],
        NONE,
        &["/me/joinedTeams", "/groups/{group-id}/team", "/teams", "/teamwork", "/teamsTemplates"],
    ),
    microsoft(
        "meetings-calls",
        "Meetings and Calls",
        "Online meetings, calls, call records, and communications APIs.",
        "https://svgl.app/library/microsoft-teams.svg",
        false,
        "collaboration",
        &["OnlineMeetings.ReadWrite"],
        NONE,
        &["/communications", "/me/onlineMeetings", "/users/{user-id}/onlineMeetings"],
    ),
    microsoft(
        "users",
        "Users",
        "User objects plus user-scoped Graph operations.",
        "https://svgl.app/library/microsoft.svg",
        true,
        "directory-identity",
        &["User.ReadWrite.All", "Directory.Read.All"],
        NONE,
        &["/users", "/users(userPrincipalName='{userPrincipalName}')"],
    ),
    microsoft(
        "groups",
        "Groups",
        "Groups, settings, lifecycle policies, and group-scoped operations.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "directory-identity",
        &["Group.ReadWrite.All", "Directory.Read.All"],
        NONE,
        &["/groups", "/groups(uniqueName='{uniqueName}')", "/groupSettings", "/groupSettingTemplates", "/groupLifecyclePolicies"],
    ),
    microsoft(
        "directory",
        "Directory",
        "Directory roles, objects, contacts, contracts, and invitations.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "directory-identity",
        &["Directory.Read.All"],
        NONE,
        &[
            "/contacts",
            "/contracts",
            "/directory",
            "/directoryObjects",
            "/directoryRoles",
            "/directoryRoles(roleTemplateId='{roleTemplateId}')",
            "/directoryRoleTemplates",
            "/invitations",
            "/scopedRoleMemberships",
        ],
    ),
    microsoft(
        "applications",
        "Applications",
        "Applications, service principals, app templates, catalogs, and grants.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "directory-identity",
        &["Application.ReadWrite.All", "AppRoleAssignment.ReadWrite.All"],
        NONE,
        &[
            "/applications",
            "/applications(appId='{appId}')",
            "/applications(uniqueName='{uniqueName}')",
            "/applicationTemplates",
            "/appCatalogs",
            "/oauth2PermissionGrants",
            "/permissionGrants",
            "/servicePrincipals",
            "/servicePrincipals(appId='{appId}')",
        ],
    ),
    microsoft(
        "identity",
        "Identity and Governance",
        "Identity, governance, policies, access reviews, roles, and providers.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "directory-identity",
        &["Policy.ReadWrite.ConditionalAccess", "RoleManagement.Read.Directory"],
        NONE,
        &[
            "/agreementAcceptances",
            "/agreements",
            "/authenticationMethodConfigurations",
            "/authenticationMethodsPolicy",
            "/certificateBasedAuthConfiguration",
            "/identity",
            "/identityGovernance",
            "/identityProviders",
            "/identityProtection",
            "/policies",
            "/roleManagement",
        ],
    ),
    microsoft(
        "admin-reports",
        "Admin and Reports",
        "Admin centers, audit logs, domains, reports, organization, and tenants.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "admin-security",
        &["AuditLog.Read.All", "Reports.Read.All"],
        NONE,
        &["/admin", "/auditLogs", "/domains", "/domainDnsRecords", "/organization", "/reports", "/subscribedSkus", "/tenantRelationships"],
    ),
    microsoft(
        "security-compliance",
        "Security and Compliance",
        "Security, compliance, privacy, information protection, and data policy.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "admin-security",
        &["SecurityEvents.Read.All"],
        NONE,
        &["/compliance", "/dataPolicyOperations", "/informationProtection", "/privacy", "/security"],
    ),
    microsoft(
        "devices",
        "Devices and Intune",
        "Devices, device management, Intune apps, managed devices, and policies.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "admin-security",
        &["DeviceManagementApps.ReadWrite.All", "DeviceManagementManagedDevices.ReadWrite.All"],
        NONE,
        &["/devices", "/devices(deviceId='{deviceId}')", "/deviceAppManagement", "/deviceManagement"],
    ),
    microsoft(
        "education",
        "Education",
        "Classes, schools, education users, assignments, and reports.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "admin-security",
        &[],
        NONE,
        &["/education"],
    ),
    microsoft(
        "search",
        "Microsoft Search",
        "Search across Microsoft Graph content connectors.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "platform-business",
        &["ExternalItem.Read.All", "Acronym.Read.All", "Bookmark.Read.All", "QnA.Read.All"],
        NONE,
        &["/search"],
    ),
    microsoft(
        "external-connections",
        "External Connections",
        "External connections, schemas, items, and content connectors.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "platform-business",
        &["ExternalConnection.ReadWrite.OwnedBy", "ExternalItem.ReadWrite.OwnedBy"],
        NONE,
        &["/connections", "/external"],
    ),
    microsoft(
        "solutions",
        "Solutions and Employee Experience",
        "Bookings, virtual events, backup, employee experience, and Copilot.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "platform-business",
        &[],
        NONE,
        &["/copilot", "/employeeExperience", "/solutions"],
    ),
    microsoft(
        "platform-services",
        "Platform Services",
        "Places, print, storage, subscriptions, functions, filters, and extensions.",
        "https://svgl.app/library/microsoft.svg",
        false,
        "platform-business",
        &["Place.Read.All", "Printer.ReadWrite.All"],
        NONE,
        &["/filterOperators", "/functions", "/places", "/print", "/schemaExtensions", "/storage", "/subscriptions"],
    ),
    with_servers(google(
        "google-calendar",
        "Google Calendar",
        "Calendars, events, ACLs, and scheduling.",
        "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest",
        "https://fonts.gstatic.com/s/i/productlogos/calendar_2020q4/v8/192px.svg",
        true,
        "standard-user",
        &["https://www.googleapis.com/auth/calendar"],
    ), &["https://www.googleapis.com"]),
    with_servers(google(
        "google-gmail",
        "Gmail",
        "Messages, threads, labels, and drafts.",
        "https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/gmail_2020q4/v8/web-96dp/logo_gmail_2020q4_color_2x_web_96dp.png",
        true,
        "standard-user",
        &["https://mail.google.com/"],
    ), &["https://gmail.googleapis.com"]),
    with_servers(google(
        "google-sheets",
        "Google Sheets",
        "Spreadsheets, values, ranges, and formatting.",
        "https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest",
        "https://fonts.gstatic.com/s/i/productlogos/sheets_2020q4/v8/192px.svg",
        true,
        "standard-user",
        &["https://www.googleapis.com/auth/spreadsheets"],
    ), &["https://sheets.googleapis.com"]),
    with_servers(google(
        "google-drive",
        "Google Drive",
        "Files, folders, permissions, and shared drives.",
        "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
        "https://fonts.gstatic.com/s/i/productlogos/drive_2020q4/v8/192px.svg",
        true,
        "standard-user",
        &["https://www.googleapis.com/auth/drive"],
    ), &["https://www.googleapis.com"]),
    with_servers(google(
        "google-docs",
        "Google Docs",
        "Documents, structural edits, and formatting.",
        "https://www.googleapis.com/discovery/v1/apis/docs/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/docs_2020q4/v12/192px.svg",
        true,
        "standard-user",
        &["https://www.googleapis.com/auth/documents"],
    ), &["https://docs.googleapis.com"]),
    with_servers(google(
        "google-slides",
        "Google Slides",
        "Presentations, slides, page elements, and deck updates.",
        "https://www.googleapis.com/discovery/v1/apis/slides/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/slides_2020q4/v12/192px.svg",
        false,
        "standard-user",
        &["https://www.googleapis.com/auth/presentations"],
    ), &["https://slides.googleapis.com"]),
    with_servers(google(
        "google-forms",
        "Google Forms",
        "Forms, questions, responses, and quizzes.",
        "https://forms.googleapis.com/$discovery/rest?version=v1",
        "https://fonts.gstatic.com/s/i/productlogos/forms_2020q4/v6/192px.svg",
        false,
        "standard-user",
        &["https://www.googleapis.com/auth/forms.body"],
    ), &["https://forms.googleapis.com"]),
    with_servers(google(
        "google-tasks",
        "Google Tasks",
        "Task lists, task items, notes, and due dates.",
        "https://www.googleapis.com/discovery/v1/apis/tasks/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/tasks/v5/192px.svg",
        false,
        "standard-user",
        &["https://www.googleapis.com/auth/tasks"],
    ), &["https://tasks.googleapis.com"]),
    with_servers(google(
        "google-people",
        "Google People",
        "Contacts, profiles, directory people, and contact groups.",
        "https://www.googleapis.com/discovery/v1/apis/people/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/contacts_2022/v2/192px.svg",
        false,
        "standard-user",
        &["https://www.googleapis.com/auth/contacts"],
    ), &["https://people.googleapis.com"]),
    with_servers(google(
        "google-photos-library",
        "Google Photos Library",
        "Albums, uploads, and app-created media through Google Photos.",
        "https://www.googleapis.com/discovery/v1/apis/photoslibrary/v1/rest",
        GOOGLE_PHOTOS_ICON,
        false,
        "advanced-user",
        &[
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata",
        ],
    ), &["https://photoslibrary.googleapis.com"]),
    with_servers(google(
        "google-photos-picker",
        "Google Photos Picker",
        "Picker sessions and user-selected Google Photos media items.",
        "https://photospicker.googleapis.com/$discovery/rest?version=v1",
        GOOGLE_PHOTOS_ICON,
        false,
        "advanced-user",
        &["https://www.googleapis.com/auth/photospicker.mediaitems.readonly"],
    ), &["https://photospicker.googleapis.com"]),
    with_servers(google(
        "google-chat",
        "Google Chat",
        "Spaces, messages, members, reactions, and chat workflows.",
        "https://www.googleapis.com/discovery/v1/apis/chat/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/chat_2020q4/v8/192px.svg",
        false,
        "workspace-admin",
        &["https://www.googleapis.com/auth/chat.spaces"],
    ), &["https://chat.googleapis.com"]),
    with_servers(google(
        "google-keep",
        "Google Keep",
        "Notes, lists, attachments, and annotations.",
        "https://keep.googleapis.com/$discovery/rest?version=v1",
        "https://fonts.gstatic.com/s/i/productlogos/keep_2020q4/v8/192px.svg",
        false,
        "unsupported-user",
        &["https://www.googleapis.com/auth/keep"],
    ), &["https://keep.googleapis.com"]),
    with_servers(google(
        "google-youtube-data",
        "YouTube Data",
        "Channels, playlists, videos, comments, and uploads.",
        "https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest",
        "https://fonts.gstatic.com/s/i/productlogos/youtube/v9/192px.svg",
        false,
        "advanced-user",
        &["https://www.googleapis.com/auth/youtube"],
    ), &["https://youtube.googleapis.com"]),
    with_servers(google(
        "google-search-console",
        "Google Search Console",
        "Sites, sitemaps, URL inspection, and search performance.",
        "https://www.googleapis.com/discovery/v1/apis/searchconsole/v1/rest",
        GOOGLE_G,
        false,
        "standard-user",
        &["https://www.googleapis.com/auth/webmasters"],
    ), &["https://searchconsole.googleapis.com"]),
    with_servers(google(
        "google-classroom",
        "Google Classroom",
        "Courses, rosters, coursework, and grading.",
        "https://www.googleapis.com/discovery/v1/apis/classroom/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/classroom/v7/192px.svg",
        false,
        "advanced-user",
        &["https://www.googleapis.com/auth/classroom.courses"],
    ), &["https://classroom.googleapis.com"]),
    with_servers(google(
        "google-admin-directory",
        "Google Admin Directory",
        "Users, groups, org units, roles, and domain resources.",
        "https://admin.googleapis.com/$discovery/rest?version=directory_v1",
        "https://fonts.gstatic.com/s/i/productlogos/admin_2020q4/v6/192px.svg",
        false,
        "workspace-admin",
        &["https://www.googleapis.com/auth/admin.directory.user"],
    ), &["https://admin.googleapis.com"]),
    with_servers(google(
        "google-admin-reports",
        "Google Admin Reports",
        "Audit events, usage reports, and admin activity logs.",
        "https://admin.googleapis.com/$discovery/rest?version=reports_v1",
        "https://fonts.gstatic.com/s/i/productlogos/admin_2020q4/v6/192px.svg",
        false,
        "workspace-admin",
        &["https://www.googleapis.com/auth/admin.reports.audit.readonly"],
    ), &["https://admin.googleapis.com"]),
    with_servers(google(
        "google-apps-script",
        "Google Apps Script",
        "Projects, deployments, and script execution.",
        "https://www.googleapis.com/discovery/v1/apis/script/v1/rest",
        "https://fonts.gstatic.com/s/i/productlogos/apps_script/v10/192px.svg",
        false,
        "advanced-user",
        &["https://www.googleapis.com/auth/script.projects"],
    ), &["https://script.googleapis.com"]),
    with_servers(google(
        "google-bigquery",
        "Google BigQuery",
        "Datasets, tables, jobs, and analytical queries.",
        "https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest",
        "https://fonts.gstatic.com/s/i/productlogos/google_cloud/v6/192px.svg",
        false,
        "advanced-user",
        &["https://www.googleapis.com/auth/bigquery"],
    ), &["https://bigquery.googleapis.com"]),
    with_servers(google(
        "google-cloud-resource-manager",
        "Google Cloud Resource Manager",
        "Projects, folders, organizations, and IAM hierarchy.",
        "https://cloudresourcemanager.googleapis.com/$discovery/rest?version=v3",
        "https://fonts.gstatic.com/s/i/productlogos/google_cloud/v6/192px.svg",
        false,
        "advanced-user",
        &["https://www.googleapis.com/auth/cloud-platform"],
    ), &["https://cloudresourcemanager.googleapis.com"]),
    graphql(
        "github-graphql",
        "GitHub GraphQL",
        "Repos, issues, PRs, and users via GitHub's GraphQL API.",
        "https://api.github.com/graphql",
        "https://svgl.app/library/github_dark.svg",
        true,
    ),
    graphql(
        "gitlab",
        "GitLab",
        "Projects, merge requests, pipelines, and users.",
        "https://gitlab.com/api/graphql",
        "https://gitlab.com/favicon.ico",
        true,
    ),
    graphql(
        "linear",
        "Linear",
        "Issues, projects, teams, and cycles.",
        "https://api.linear.app/graphql",
        "https://linear.app/favicon.ico",
        true,
    ),
    graphql(
        "monday",
        "Monday.com",
        "Boards, items, columns, and workspace automation.",
        "https://api.monday.com/v2",
        "https://monday.com/favicon.ico",
        false,
    ),
    graphql(
        "anilist",
        "AniList",
        "Anime and manga database - no auth required.",
        "https://graphql.anilist.co",
        "https://anilist.co/img/icons/favicon-32x32.png",
        false,
    ),
    mcp_remote(
        "emulate-mcp",
        "Emulate MCP",
        "Deterministic MCP fixtures for validating native text and image content.",
        "https://emulators.dev/mcp/query/mcp?token=demo-token",
        "https://emulators.dev/favicon.ico",
        false,
    ),
    mcp_remote(
        "deepwiki",
        "DeepWiki",
        "Search and read documentation from any GitHub repo.",
        "https://mcp.deepwiki.com/mcp",
        "https://deepwiki.com/favicon.ico",
        true,
    ),
    mcp_remote(
        "context7",
        "Context7",
        "Up-to-date docs and code examples for any library.",
        "https://mcp.context7.com/mcp",
        "https://context7.com/favicon.ico",
        true,
    ),
    mcp_remote(
        "browserbase",
        "Browserbase",
        "Cloud browser sessions for web scraping and automation.",
        "https://mcp.browserbase.com/mcp",
        "https://www.browserbase.com/favicon.ico",
        true,
    ),
    mcp_remote(
        "firecrawl",
        "Firecrawl",
        "Crawl and scrape websites into structured data.",
        "https://mcp.firecrawl.dev/mcp",
        "https://www.firecrawl.dev/favicon.ico",
        true,
    ),
    mcp_remote(
        "neon-mcp",
        "Neon MCP",
        "Serverless Postgres - branches, queries, and management.",
        "https://mcp.neon.tech/mcp",
        "https://neon.tech/favicon/favicon.ico",
        true,
    ),
    mcp_remote(
        "axiom-mcp",
        "Axiom MCP",
        "Query, analyze, and monitor your logs and event data.",
        "https://mcp.axiom.co/mcp",
        "https://axiom.co/favicon.ico",
        true,
    ),
    mcp_remote(
        "stripe-mcp",
        "Stripe MCP",
        "Manage payments, subscriptions, and billing via MCP.",
        "https://mcp.stripe.com",
        "https://stripe.com/favicon.ico",
        true,
    ),
    mcp_remote(
        "linear-mcp",
        "Linear MCP",
        "Issues, projects, teams, and cycles via MCP.",
        "https://mcp.linear.app/mcp",
        "https://linear.app/favicon.ico",
        true,
    ),
    mcp_remote(
        "notion",
        "Notion",
        "Databases, pages, blocks, and search via MCP.",
        "https://mcp.notion.com/mcp",
        "https://www.notion.com/front-static/favicon.ico",
        true,
    ),
    mcp_remote(
        "sentry-mcp",
        "Sentry MCP",
        "Error monitoring, issues, and performance data.",
        "https://mcp.sentry.dev/mcp",
        "https://svgl.app/library/sentry.svg",
        false,
    ),
    mcp_remote(
        "cloudflare-mcp",
        "Cloudflare MCP",
        "Workers, KV, D1, R2, and DNS management via MCP.",
        "https://mcp.cloudflare.com/mcp",
        "https://cloudflare.com/favicon.ico",
        false,
    ),
    RegistryEntry {
        id: "microsoft",
        name: "Microsoft Graph",
        summary: "Bundle Microsoft 365 workloads into one Graph source and one OAuth consent.",
        kind: RegistryKind::MicrosoftGraph,
        url: Some(MICROSOFT_GRAPH_OPENAPI_URL),
        endpoint: Some("https://graph.microsoft.com/v1.0"),
        icon: Some(MICROSOFT_ICON),
        featured: true,
        oauth_audience: Some("bundle"),
        scopes: &["offline_access", "https://graph.microsoft.com/.default"],
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    },
    RegistryEntry {
        id: "google",
        name: "Google",
        summary: "Bundle Gmail, Calendar, Drive, Docs, and other Google APIs into one source.",
        kind: RegistryKind::GoogleDiscovery,
        url: None,
        endpoint: None,
        icon: Some(GOOGLE_G),
        featured: true,
        oauth_audience: Some("bundle"),
        scopes: NONE,
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    },
    RegistryEntry {
        id: "google-photos",
        name: "Google Photos",
        summary: "Albums, uploads, app-created media, and user-selected picker media.",
        kind: RegistryKind::GoogleDiscovery,
        url: None,
        endpoint: None,
        icon: Some(GOOGLE_PHOTOS_ICON),
        featured: true,
        oauth_audience: Some("bundle"),
        scopes: NONE,
        exact_paths: NONE,
        path_prefixes: NONE,
        tag_prefixes: NONE,
        servers: NONE,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn carries_executor_curated_registry() {
        assert_eq!(entries().len(), 85);
        assert_eq!(find("petstore").unwrap().kind, RegistryKind::OpenApi);
        assert_eq!(
            find("microsoft").unwrap().kind,
            RegistryKind::MicrosoftGraph
        );
        assert_eq!(
            find("google-gmail").unwrap().kind,
            RegistryKind::GoogleDiscovery
        );
        assert_eq!(find("anilist").unwrap().kind, RegistryKind::GraphQl);
        assert_eq!(find("deepwiki").unwrap().kind, RegistryKind::McpRemote);
        assert!(find("chrome-devtools").is_none());
    }

    #[test]
    fn registry_serializes_without_code() {
        let value = serde_json::to_value(entries()).unwrap();
        let text = serde_json::to_string(&value).unwrap();
        assert!(text.contains("\"kind\":\"openapi\""));
        assert!(text.contains("\"kind\":\"graphql\""));
        assert!(!text.contains("chrome-devtools"));
        assert!(!text.contains("\"command\""));
        assert!(text.contains("petstore3.swagger.io"));
        assert!(text.contains("https://graph.microsoft.com/v1.0"));
    }
}
