// Shared StyleX styles for the examples subsystem. StyleX style objects work across
// files (same pattern as instrument's `text`), so the shell, panel, and drivers all
// import from here — one source for the layout, terminal, content, and control styles.

import * as stylex from "@stylexjs/stylex";
import { color } from "instrument/tokens/color.stylex.js";
import { space } from "instrument/tokens/space.stylex.js";
import { radius } from "instrument/tokens/radius.stylex.js";
import { font } from "instrument/tokens/type.stylex.js";

export const styles = stylex.create({
  // ── shell / layout ────────────────────────────────────────────────────────
  area: {
    width: "100%",
    // One lesson fills the viewport — no page scroll for the group; the content box
    // scrolls internally. overflow:hidden also clips the scale ticks at the left edge.
    height: "100vh",
    overflow: "hidden",
    paddingTop: "clamp(24px, 3vh, 44px)",
    paddingBottom: "clamp(24px, 3vh, 44px)",
    paddingLeft: "clamp(56px, 5vw, 72px)",
    paddingRight: "clamp(24px, 4vw, 80px)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: color.border,
  },
  layout: {
    height: "100%",
    maxWidth: "1560px",
    display: "grid",
    gridTemplateColumns: "380px minmax(0, 1fr)",
    gap: "clamp(24px, 2.2vw, 40px)",
    alignItems: "stretch",
  },
  tocCol: { alignSelf: "center", minHeight: 0 },
  main: { minWidth: 0, minHeight: 0, display: "flex", flexDirection: "column", gap: "clamp(16px, 2.4vh, 32px)" },
  titleBlock: { display: "flex", flexDirection: "column", gap: space.s3 },
  eyebrow: { color: color.inkSubtle },
  title: { margin: 0, fontSize: "clamp(28px, 24px + 1.4vw, 44px)" },
  subtitle: { maxWidth: "62ch" },
  workRow: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) clamp(340px, 30vw, 460px)",
    gridTemplateRows: "auto minmax(0, 1fr)",
    columnGap: space.s6,
    rowGap: space.s3,
  },

  // ── pill tabs ─────────────────────────────────────────────────────────────
  pillRow: {
    gridColumn: "1",
    gridRow: "1",
    display: "flex",
    flexWrap: "wrap",
    gap: space.s2,
    alignItems: "center",
  },
  pill: {
    paddingBlock: "5px",
    paddingInline: space.s3,
    borderRadius: radius.pill,
    borderWidth: 0,
    fontSize: "12.5px",
    fontWeight: 500,
    whiteSpace: "nowrap",
    cursor: "pointer",
    color: { default: color.inkMuted, ":hover": color.ink },
    backgroundColor: { default: "transparent", ":hover": color.frost },
    transitionProperty: "color, background-color",
    transitionDuration: "150ms",
  },
  pillActive: { color: color.ink, backgroundColor: color.frost },

  // ── left content column (shared by every driver via ExampleShell) ──────────
  content: {
    gridColumn: "1",
    gridRow: "2",
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    padding: space.s5,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.border,
    borderRadius: radius.card,
    backgroundColor: color.bgPanel,
    scrollbarWidth: "thin",
    scrollbarColor: `${color.borderStrong} transparent`,
  },
  contentInner: { display: "flex", flexDirection: "column", gap: space.s4 },
  lede: { color: color.inkMuted, maxWidth: "62ch" },
  notes: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: space.s2 },
  note: {
    position: "relative",
    paddingLeft: space.s4,
    color: color.inkMuted,
    "::before": { content: "'—'", position: "absolute", left: 0, color: color.inkSubtle },
  },
  placeholder: { maxWidth: "60ch" },

  // ── play button (one bare green triangle + a few positioning variants) ─────
  playBtn: {
    display: "flex",
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    cursor: "pointer",
    opacity: { default: 0.85, ":hover": 1 },
    transform: { default: "scale(1)", ":hover": "scale(1.12)" },
    transitionProperty: "transform, opacity",
    transitionDuration: "150ms",
  },
  playAbs: { position: "absolute", top: space.s3, right: space.s3 }, // top-right of the code block
  playRight: { marginLeft: "auto", alignSelf: "center" }, // pushed to the end of a flavor row
  playFill: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    transform: { default: "scale(1)", ":hover": "scale(1.08)" },
  },

  // ── program editor / read-only code ────────────────────────────────────────
  codeWrap: { position: "relative" },
  editor: {
    display: "block",
    borderRadius: radius.chip,
    overflow: "hidden",
    backgroundColor: color.bgSunken,
    fontSize: "12.5px",
    "--mc-fg": color.ink,
    "--mc-fg-muted": color.inkMuted,
    "--mc-fg-subtle": color.inkSubtle,
  },
  code: {
    margin: 0,
    padding: space.s4,
    paddingRight: "44px",
    borderRadius: radius.chip,
    backgroundColor: color.bgSunken,
    fontFamily: font.mono,
    fontSize: "12.5px",
    lineHeight: 1.6,
    color: color.ink,
    overflowX: "auto",
    whiteSpace: "pre",
  },

  // ── declarative step list (commands driver) ────────────────────────────────
  stepList: { display: "flex", flexDirection: "column", gap: space.s1, position: "relative" },
  step: { fontFamily: font.mono, fontSize: "12.5px", color: color.inkMuted },
  stepCmd: { color: color.ink, "::before": { content: "'$ '", color: color.inkSubtle } },

  // ── image flavor spans ─────────────────────────────────────────────────────
  flavorList: { display: "flex", flexDirection: "column" },
  flavorSpan: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
    paddingBlock: space.s4,
    borderBottomWidth: { default: "1px", ":last-child": "0" },
    borderBottomStyle: "solid",
    borderBottomColor: color.border,
  },
  flavorHead: { display: "flex", alignItems: "baseline", gap: space.s2 },
  flavorName: { fontFamily: font.mono, fontSize: "14px", fontWeight: 600, color: color.ink },
  flavorNameOn: { color: "#3fcf6f" },
  flavorMeta: { fontFamily: font.mono, fontSize: "11.5px", color: color.inkSubtle },
  flavorHas: { color: color.inkMuted, fontSize: "13px", lineHeight: 1.45, maxWidth: "58ch" },
  flavorBest: { fontSize: "12.5px" },

  // ── remote lifecycle form ──────────────────────────────────────────────────
  form: { display: "flex", flexDirection: "column", gap: space.s3, maxWidth: "440px" },
  field: { display: "flex", flexDirection: "column", gap: "4px" },
  fieldLabel: {
    fontSize: "11px",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: color.inkSubtle,
    fontWeight: 600,
  },
  fieldRow: { display: "flex", gap: space.s2, alignItems: "stretch" },
  urlGroup: {
    display: "flex",
    alignItems: "stretch",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: color.border, ":focus-within": color.borderStrong },
    borderRadius: radius.chip,
    backgroundColor: color.bgSunken,
    overflow: "hidden",
  },
  inputBare: {
    flex: 1,
    minWidth: 0,
    paddingBlock: "8px",
    paddingInline: space.s3,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: color.ink,
    fontFamily: font.mono,
    fontSize: "12.5px",
    outline: "none",
    opacity: { default: 1, ":disabled": 0.55 },
  },
  urlSuffix: {
    display: "flex",
    alignItems: "center",
    paddingInline: space.s3,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: color.border,
    color: color.inkSubtle,
    fontFamily: font.mono,
    fontSize: "12.5px",
    flexShrink: 0,
  },
  input: {
    width: "100%",
    minWidth: 0,
    paddingBlock: "8px",
    paddingInline: space.s3,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: color.border, ":focus": color.borderStrong },
    borderRadius: radius.chip,
    backgroundColor: color.bgSunken,
    color: color.ink,
    fontFamily: font.mono,
    fontSize: "12.5px",
    outline: "none",
    opacity: { default: 1, ":disabled": 0.55 },
  },
  regenBtn: {
    flexShrink: 0,
    width: "38px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: color.border, ":hover": color.borderStrong },
    borderRadius: radius.chip,
    backgroundColor: { default: color.bgSunken, ":hover": color.bgCard },
    color: color.inkMuted,
    fontSize: "15px",
    cursor: "pointer",
  },
  primaryBtn: {
    alignSelf: "flex-start",
    marginTop: space.s1,
    paddingBlock: "9px",
    paddingInline: space.s5,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: color.borderStrong, ":hover": color.ink },
    borderRadius: radius.chip,
    backgroundColor: { default: color.frost, ":hover": color.frostHover },
    color: color.ink,
    fontSize: "13px",
    fontWeight: 550,
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.45 },
  },
  connectBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    paddingBlock: "7px",
    paddingInline: space.s3,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#2f7d4f", ":hover": "#3fcf6f" },
    borderRadius: radius.chip,
    backgroundColor: "transparent",
    color: "#3fcf6f",
    fontSize: "13px",
    fontWeight: 550,
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.4 },
  },
  killBtn: {
    paddingBlock: "7px",
    paddingInline: space.s3,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "#7d3030", ":hover": "#e5606a" },
    borderRadius: radius.chip,
    backgroundColor: "transparent",
    color: "#e5606a",
    fontSize: "13px",
    fontWeight: 550,
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.4 },
  },

  // ── terminal column (TerminalPanel) ────────────────────────────────────────
  termCol: { gridColumn: "2", gridRow: "2", minWidth: 0, display: "flex", flexDirection: "column", gap: space.s3 },
  terminalBox: {
    width: "100%",
    height: "clamp(220px, 42vh, 460px)",
    flexShrink: 0,
    borderRadius: radius.card,
    overflow: "hidden",
    display: "flex",
  },
  terminalBoxIdle: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.border,
    backgroundColor: color.bgSunken,
    alignItems: "center",
    justifyContent: "center",
  },
  termHint: { fontSize: "13px" },
  // No `display` here — <mc-terminal> is display:flex (column); a StyleX display
  // collapses that, unconstrains .screen, and xterm fits to a bogus size. Size only.
  terminal: { width: "100%", height: "100%" },
  actions: { display: "flex", flexWrap: "wrap", gap: space.s2, alignItems: "center", minHeight: "40px" },
  logs: {
    minHeight: "40px",
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
    paddingTop: space.s1,
  },
  logLine: {
    fontFamily: font.mono,
    fontSize: "12px",
    lineHeight: 1.5,
    color: color.inkMuted,
    "::before": { content: "'› '", color: color.inkSubtle },
  },
});
